### ISSUE TITLE
GLM RTC include path is not portable

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1001]
When GLM is enabled, to be usable in RTC compiled device functions the include path must be forwarded to nvrtc to find the glm include directory. 

This is not portable, as an absolute path is forwarded via the `GLM_PATH` compiler definition. This path will then be incorrect for python wheels etc.

https://github.com/FLAMEGPU/FLAMEGPU2/blob/32addb1e5d070aab0cedc9cefb6cd5cd7f82020e/src/CMakeLists.txt#L401

https://github.com/FLAMEGPU/FLAMEGPU2/blob/32addb1e5d070aab0cedc9cefb6cd5cd7f82020e/src/flamegpu/util/detail/JitifyCache.cu#L297

This will also be relevant if / when we have CMake installation of the static library #260

**Comment by Robadob** [comment]
Started looking at this.

In terms of resolving Python wheels, the solution would be to package GLM inside the wheel similar to how we package the flamegpu headers.

GLM has [`MIT` license](https://github.com/g-truc/glm/blob/master/copying.txt), so this should be fine if we include the license too.

We could then do a FLAMEGPU_GLM_INCLUDE_DIR env var, similar to the main include dir env var, allowing users to override the default if necessary.

**Comment by Robadob** [comment]
Can't find any GLM tests in python test suite (would explain `pyflamegpu.GLM`) not being a thing.

Doesn't appear SWIG has GLM mappings setup either (did this get left on hold because of the jitify slow compilation?)
