### ISSUE TITLE
AgentDescription.getFunction

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2#1003]
`AgentDescription.getFunction` returns a `CAgentFunctionDescription` and not a `AgentFunction` which has confused Jack when doing stuff with layers.

**Comment by Robadob** [comment]
Issue being that `LayerDescription::addAgentFunction(const AgentFunctionDescription&)` should be `LayerDescription::addAgentFunction(const CAgentFunctionDescription&)`. It's a trivial fix, will sort it tomorrow as I'm currently dealing with a complex rebase.
