### ISSUE TITLE
pyflamegpu not found

### ISSUE THREAD

**Issue by khateraAlizada** [FLAMEGPU/FLAMEGPU2#1005]
Describe the bug
When I try to import pyflamegpu in the template model link below, it gives error (below) can not import pyflamegpu. How can I resolve the issue :
https://colab.research.google.com/drive/12K9MNYHe1ijZVGMYgisykJI_7r8rF7Lb
import sys
!{sys.executable} -m pip install -I https://github.com/FLAMEGPU/FLAMEGPU2/releases/download/v2.0.0-alpha.1/pyflamegpu-2.0.0a1+cuda112-cp37-cp37m-linux_x86_64.whl

import os

# Import pyflamegpu and some other libraries we will use in the tutorial
sys.path.append(os.path.expanduser('~') + "/.local/lib/python3.6/site-packages")
import pyflamegpu
import sys, random, math
import matplotlib.pyplot as plt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: pyflamegpu-2.0.0a1+cuda112-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-0389dc36307b> in <module>
      6 # Import pyflamegpu and some other libraries we will use in the tutorial
      7 sys.path.append(os.path.expanduser('~') + "/.local/lib/python3.6/site-packages")
----> 8 import pyflamegpu
      9 import sys, random, math
     10 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pyflamegpu'

Steps to reproduce the behaviour:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behaviour

Screenshots
If applicapable
<img width="1440" alt="Screen Shot 2022-12-02 at 4 40 47 PM" src="https://user-images.githubusercontent.com/20228364/205395147-f53978f8-30a5-4ad6-9f38-50ea5df922ce.png"><img width="1440"

**Comment by Robadob** [comment]
It appears Google Collab has updated the Python version again (3.7->3.8) since you previously had the same  issue (#953).

I've now fixed this and the collab accessible via http://flamegpu.com/try should be working again.

Apologies for any trouble this caused you.

**Comment by Robadob** [comment]
@khateraAlizada 

We've just updated the google collab to work with the Release Candidate 0 wheel, which we released yesterday.

If you've been working with a modified notebook based on the tutorial, you can find the changes we made [here](https://github.com/FLAMEGPU/FLAMEGPU2-tutorial-python/pull/21/files).
