### ISSUE TITLE
Telemetry Payload errors

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1035]
The telemertry payload has a number of (potential errors) from a quick look at some data:

+ [ ] pyflamegpu is never reported - this is (probably) due to the `#ifdef SWIG` being in a source file not a header file, and SWIG is only defined when building the pyflamegpu interface. 
+ [x] `buildNumber` has been reported as `buildNumber` rather than an actual hash. This value is set at CMake configuration time from a call to git, which should be on the path at configure time otherwise an error should occur so not sure how this is happening.
  + This appears to be an issue with the manylinux CI jobs not getting the build number at cmake time, so manylinux workflows need adjusting to fix the git related warning.
  + Fixed by #1036

**Comment by Robadob** [comment]
To catch python, the most sensible option is probably to augment the constructor for `ModelDescription` or `CUDASimulation`/`CUDAEnsemble`, to catch SWIG (pass a bool to the normal constructor defined private). Lazy version would be to detect use of RTC.

**Comment by Robadob** [comment]
Marked this planned as it would be useful to identify C/Python breakdown if we're going to be publishing Python specific paper.

**Comment by Robadob** [comment]
Bit more testing this morning/yesterday, can't do the same trick as the visualiser for `CUDASimulation::simulate()` as it's a virtual function it cannot be inlined. Needs some more thought.
