### ISSUE TITLE
Git submodule support for users

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#104]
Longer term we should probably restructure the repository so that users can include the core part of FLAME GPU 2 in their own repos as a submodule, and ensure that it is easy for users to develop models outside of the FLAME GPU 2 repository. 

This will require 
+ [ ] Ensuring CMake supports this behaviour, and makes it very easy to achieve
+ [ ] Documentation of how to set up repositories like this, ideally with an example
+ [ ] Potentially splitting the repository up into several smaller repositories
    + I.e. splitting some (all?) of the examples out so that users do not need to pull example code down if not required. 

It's probably worth keeping tests with the main library, so that users can run tests on their compiled version.

**Comment by Robadob** [comment]
>  Documentation of how to set up repositories like this, ideally with an example

Github supports template repositories.

**Comment by ptheywood** [comment]
I'm going to close this for now, as CMake dependency management used in the template repos should be sufficient. 

This appears to work realteively well

```
git submodule add git@github.com:FLAMEGPU/FLAMEGPU2
```

```
# CMakeLists.txt
add_subdirectory("FLAMEGPU2")
set(FLAMEGPU_ROOT "FLAMEGPU2")
# Include common rules from the main repositorys CMake
include(${FLAMEGPU_ROOT}/cmake/common.cmake)
```

This does add all examples to the target, so also setting a couple of cache vars like the examples `cmake/flamegpu2.cmake` would improve things.

```
set(NO_EXAMPLES ON CACHE INTERNAL "-")
set(BUILD_TESTS OFF CACHE BOOL "-")
```

I'm going to close this as it works but is not our preffered option, so not going to bloat the docs with it.
