### ISSUE TITLE
Ensembles: Expose ID or index within the ensemble to the simulation

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1066]
A simulation within an ensemble has no way of getting it's index or ID within an ensemble, which may be useful for uniqueuly naming output files etc. 

It may also be useful to exposes the ensemble size to the simulation / host api? could either use 0 or 1 for simulations which are not in an ensemble (for a consistent behaviour between the two). 

Currently, users could implement this by adding the index/id themselves to the RunPlanVector. 

E.g. (untested)

```
const unsigned int ENSEMBLE_SIZE = 128;
flamegpu::RunPlanVector runs_control(model, ENSEMBLE_SIZE);
runs_control.setPropertyLerpRange<unsigned int>("ensemble_idx", 0, ENSEMBLE_SIZE-1);  // inclusive 
```

**Comment by Robadob** [comment]
Worth exposing `SimulationConfig` and `CUDAConfig` too as requested in https://github.com/FLAMEGPU/FLAMEGPU2/discussions/1075
