### ISSUE TITLE
Hosted Docs (doxygen)

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#110]
It may be useful to set up online hosted docs to build using doxygen. 

This may require tweaking cmake, such that it is possible to build the docs **without** cuda being required.

**Comment by ptheywood** [comment]
It's been suggested that [breathe](https://breathe.readthedocs.io/en/latest/) can be used with sphinx etc

**Comment by Robadob** [comment]
> Build docs without CUDA has been added to master

203482c4d055de6154b64af7a24d974a885fa215
