### ISSUE TITLE
[Bug]:The results simulated by using Python Agent API in Tutorial Code are different from those using c++ Agent API.

### ISSUE THREAD

**Issue by chenyuyou** [FLAMEGPU/FLAMEGPU2#1158]
### Bug Description

The results simulated by using Python Agent API in Tutorial Code are different from those using c++ Agent API.
https://docs.flamegpu.com/tutorial/index.html#complete-tutorial-code

### To Reproduce

![image](https://github.com/FLAMEGPU/FLAMEGPU2/assets/7900395/4cd35e38-c3d1-4b26-8c08-ca8b370e9c2d)
This is the result by using python agent api
![image](https://github.com/FLAMEGPU/FLAMEGPU2/assets/7900395/6e9d5a7f-0923-4c54-98e6-5fc37abd6105)
This is the result by using C++ agent api

### Expected Behaviour

I think that the result of by using python agent api is wrong.

### OS

win11

### CUDA Versions

cuda 11

### GPUs

3080

**Comment by Robadob** [comment]
I have a feeling this is a bug I've seen before and thought I addressed. Will take a look later this afternoon.

Thanks for reporting.

**Comment by Robadob** [comment]
Hi,

I've tried both the "Python (using C++ Agent API)" and "Python (using Python Agent API)" versions found [here](https://docs.flamegpu.com/tutorial/index.html#complete-tutorial-code) and the both produce output like this (which is correct):

![image](https://github.com/FLAMEGPU/FLAMEGPU2/assets/742154/7e3c8afd-3c35-4e96-b26a-35487a1ef19b)

Is it possible you've modified one of the environment properties or made a mistake whilst copying from the individual code snippets?

Behaviour similar to your first screenshot can be achieved by setting `repulse` to a negative number.

![image](https://github.com/FLAMEGPU/FLAMEGPU2/assets/742154/62f12469-eeea-4940-9b4b-23ba1031209c)

If you can share your implementation I will try running that too.

**Comment by chenyuyou** [comment]
I rewrite those code in my repositories. Their codes are the same but the results are different.
The python code is  https://github.com/chenyuyou/fg2-example/blob/main/circles_spatial2D/python/model.py
The c++ code is https://github.com/chenyuyou/fg2-example/blob/main/circles_spatial2D/python_rtc/model.py

**Comment by Robadob** [comment]
I've just downloaded and ran both of your versions of the code. Both execute and produce the correct circle arrangement of agents after around 200 steps.

I don't think this would be a difference with the version of `pyflamegpu` you are using (I just built the latest from `master`), is it possible you have changes that you haven't pushed to `git` (e.g. check `git diff`)?

**Comment by chenyuyou** [comment]
> I've just downloaded and ran both of your versions of the code. Both execute and produce the correct circle arrangement of agents after around 200 steps.
> 
> I don't think this would be a difference with the version of `pyflamegpu` you are using (I just built the latest from `master`), is it possible you have changes that you haven't pushed to `git` (e.g. check `git diff`)?

How to build pyflamegpu lastest version？

**Comment by Robadob** [comment]
> How to build pyflamegpu lastest version？

Clone the git repo (or download the [latest zip](https://codeload.github.com/FLAMEGPU/FLAMEGPU2/zip/refs/heads/master))

Then follow [this guide](https://docs.flamegpu.com/quickstart/index.html#building-from-source) from the docs.

**Comment by Robadob** [comment]
Ah, this PR was merged a while back but isn't currently in a release. I expect that may explain your problem.

https://github.com/FLAMEGPU/FLAMEGPU2/pull/1077

Apologies, for not realising sooner.

**Comment by Robadob** [comment]
We're hoping to get another release out "soon", once #1090 #1089 and #1150 have been merged (the latter is waiting on a 3rd party PR to be merged). This will hopefully be Jan/Feb.

I can manually trigger a draft release build, which will generate new wheels (that expire after ~24h) if you are unable to build pyflamegpu yourself.

**Comment by chenyuyou** [comment]
> > How to build pyflamegpu lastest version？
> 
> Clone the git repo (or download the [latest zip](https://codeload.github.com/FLAMEGPU/FLAMEGPU2/zip/refs/heads/master))
> 
> Then follow [this guide](https://docs.flamegpu.com/quickstart/index.html#building-from-source) from the docs.

Thanks for your help, I will try soon.

**Comment by chenyuyou** [comment]
Install pyflamegpu 2.0.0rc1+cuda118 wheel into D:/Downloads/FLAMEGPU2/build/lib/Release/python/venv
  Looking in links: dist
EXEC : error : Could not find a version that satisfies the requirement pyflamegpu==2.0.0rc1+cuda118 (from versions: non
e) [D:\Downloads\FLAMEGPU2\build\swig\python\pyflamegpu.vcxproj]
EXEC : error : No matching distribution found for pyflamegpu==2.0.0rc1+cuda118 [D:\Downloads\FLAMEGPU2\build\swig\pytho
n\pyflamegpu.vcxproj]
