### ISSUE TITLE
Remove unnecessary astpretty dependency

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#1164]
Astpretty is currently a pyflamegpu dependency in `setup.py.in`. 

It is not actually used within pyfalemgpu's codegen module, only in a test.

It therefore is not a dependency of pyflamegpu, so should be removed from setup.py.in. 

~Usage within the test suite is also condition, guarded by an undefined variable `DEBUG_OUT`. This should be removed too, and can be added back in with the import if/when required.~

Usage within the test suite is guarded by a file-scoped variable `DEBUG_OUT`, which is set to true.
We can make this an optional dependency installed in the test environment alongside pytest.

**Comment by Robadob** [comment]
This impact #1131 too

**Comment by ptheywood** [comment]
Already closed as part of #1166, but I misspelt `closes` in the PR so this didn't auto close :laughing: 

> Closses https://github.com/FLAMEGPU/FLAMEGPU2/issues/1164
