### ISSUE TITLE
Improved Telemetry for Unique User Tracker

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2#1212]
Current telemetry data approximates unique users by the build ID. For Python distributions all users have the same ID so the true number of unique (but anonymous) users is unknown. To better understand unique users it is proposed that the software could generate a unique user ID at package install time (or at runtime with the ID cached in a settings file). If done at runtime this could be performed in the C++ backend. The appropriate file locatiosn would be

Windows: `%PROGRAMDATA%\FLAMEGPU\config`
Linux: `~\.config\FLAMEGPU\config `

**Comment by ptheywood** [comment]
Linux should respect the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), not just hard code `~/.config/...`. 

---

w.r.t. GDPR, care will need to be taken with what/how that identifier is generated (and even if having the identifier is relevant), as identification numbers can be considered personal data, thought that also applies to the current unique identifiers. 

> ‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person;
