### ISSUE TITLE
[FeatureReq]: Visualisation starting with rotated camera position (model upside down). 

### ISSUE THREAD

**Issue by DavidFletcherShef** [FLAMEGPU/FLAMEGPU2#1238]
### Is your feature request related to a problem?

The standard visualisation starts with the 'y' dimension vertically, and increasing positively up the screen. There appears to be no way to start with 'y' increasing down the screen. 

setInitialCameraLocation and setInitialCameraTarget provide x, y, z translation of camera and target, but not rotation. 

### Describe the solution you'd like

Adding a camera roll angle to setInitialCameraLocation would address this issue. 

### Describe alternatives you've considered

Rotation can be achieved with q and e to interactively roll the camera position, but there appears to be no programmatic way to have the visualisation start at a particular roll angle. 

I tried making all the y values negative within the model as this effectively rotates the model. However, it gave a dramatic slow down in performance - I'm not sure why. Since it's adding an additional complication and potential unwanted side effects in some calculations I stopped doing this and just rotate the model manually each run. 

### Additional context

This is a for a research application in which conventionally downwards is positive, which makes all the flame models come out "upside down".

**Comment by Robadob** [comment]
> I tried making all the y values negative within the model as this effectively rotates the model. However, it gave a dramatic slow down in performance - I'm not sure why. 

This isn't clear why it would harm performance. My approach would be to great a second `vis_y` variable, which is just set to the negative of `y` every time that is updated. Then tell the visualiser to use `vis_y` as `y`.

This feature should be relatively simply to add, but it requires updates to both the visualiser repository and this repository. Not currently any costed FLAMEGPU time, but I may get to this at the weekend (I'm still poking the graph vis thing you mentioned a couple of weeks ago).
