### ISSUE TITLE
FLAME GPU 2 Logo

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#139]
FLAME GPU 2 should probably have a new logo, ideally including a squarer logo for icons etc. 

![flame-gpu-2-temporary-logo](https://user-images.githubusercontent.com/628937/68863380-28cda800-06e7-11ea-8f3c-89e56a9d5432.gif)

**Comment by Robadob** [comment]
Simple commit here, showing how to add an application icon via CMake for Windows (not sure if it's applicable to Unix, or requires different method).

https://github.com/Robadob/sudoku_visualiser/commit/97ce3f877dc98bdc318af414d595820009b9cbdb

For visualiser you can set the icon using this method (page has an example), haven't tried it yet but looks ok:
https://wiki.libsdl.org/SDL_SetWindowIcon

**Comment by ptheywood** [comment]
Closing as this was resolved pre-GTC / website release.
