### ISSUE TITLE
Calling CUDA Commands in Destructors

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#190]
It is unsafe to call cuda commands in destructors of c++ objects, as on calls to `exit()` the order in which objects and the CUDA context are destroyed is not guaranteed - It is possible for the cuda context to be destroyed before any objects, resulting in CUDA errors (and therefore segfaults).

Currently (4446e5b) this is causing a segfault under linux when running the `tests`, as `CUDAScatter::~CUDAScatter()` calls `CUDAScatter::free()` which contains `gpuErrchk(cudaFree(d_data));`. 

Although tests pass, the segfault is not ideal. 

This needs checking on **every** class destructor and code adjusting to avoid this.

**Comment by ptheywood** [comment]
If we switch to manual context management via the driver api (and driver api commands) then in destructors cuda commands may error with `CUDA_ERROR_CONTEXT_IS_DESTROYED` (amogst other possible errors) which we could catch and ignore / mark memory as freed. 

However i'm not 100% confident in this.

**Comment by Robadob** [comment]
As of #321, I don't think there are any cuda malloc's owned by singletons. So they now get destroyed by CUDAAgentModel `destructor`. This *might* be resolved.

**Comment by ptheywood** [comment]
I'm going to tentatively close this for now. I'm not convinced that what we're currently doing is strictly safe, but the issues we had previously are generally not occuring (although there may still be segfaults after some exceptions are raised, causing early exit). 

It's something we should still be aware of, and can consider again if needed.
