### ISSUE TITLE
Refactoring to improve quality pre-release

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#237]
Some general refactoring should be done before release to improve code quality, documentation clarity and the API interace. 

+ [ ] Reduce/remove ambiguous terms
    + I.e. use of `FLAMEGPU` for both host and device functions, even though the type is different.
+ [ ] Directory Names / file structuring
    + i.e. `sim` vs `simulation`
+ [x] C++ namespaces?
    + Should namespaces be used to mirror the filestructre - i.e. `flamegpu::gpu::CUDASimulation`
+ [ ] Ensure Class names are appropriate
    + [x] `CUDAAgentModel` -> `CUDASimulation`
    + [x] `HostAgentInstance` - Does not represent one individual but the whole population.  
+ [ ] Ensure classes are contained within the most appropriate file 
    + Typically `classname.h/cpp/cu`, unless an innerclass or some dependency messs prevents this.
+ [ ] Variable name / interface naming concistency
    + mix of `camelCase` and `snake_case` currently used. This is not the end of the world but we should probably try to be consistent.
    + class names in all caps and so on. (i.e. `FLAMEGPU_READ_ONLY_DEVICE_API`)
    + Concistency between different parts of the API
        + [x] I.e. `FLAMEGPU.setVariable<T>(name, value)` vs `environment.set<T>(name, value)` 
+ ~Type name / qualifier consistency~
    + ~`float * ptr` vs `float* ptr` vs `float *ptr`~
    + ~`float & ref` vs `float& ref` vs `float &ref`~
    + ~`const int` vs `int const` (more important for `const int * const` vs `int const * const`~
    + Can't be enforced via linters, so not viable.
+ [ ] fixed width type
    + Do we want to follow google/cpplint style guid one using fixed widths types for anything other than `int`?
        + This reduces portability, which is a myth with CUDA as the backend anyway so no negatives?
+ [ ] Public/Private headers
    + Not all classes implemented should be accessible in user code - these headers can be included in the `src` directory.
    + Not all methods on some library headers should be available to users - i.e. Adding variables with reserved names to `agent_description`s - this should be accessible within `src` (and `tests?`) but nowhere else. PIMPL?
    + This also needs to be conisderd at CMake time - most include_directories should be marked as `private`, while the `include` direcotry should be public.
    + External headers (jitify etc) should ideally not be used in our `include` files, as this then means the jitify headers need to be on the include path for any dependent applications (i.e. examples). Thy should just be used internally within flamegpu2, so users only have to include/link the main library + flamegpu2 headers. 
+ [ ] CUDA separation of concerns.
    + the gpu / runtime namespaces overlap a lot.
    + Parts outside of the gpu namespace use CUDA - should this be the case?
    + Some files are `.cu` which should be `.cpp`
    + Some `.h/.cpp` files include CUDA specific headers (`cuda_runtime.h`)
        + Use `.cuh` to distinguish this.
        + Do we want to clearly identify this is c++ not c via `.hpp/.hxx`? (no?)
+ [ ] CMake
    + [ ] Clean up /document CMake files
    + [x] Ensure cmake options are appropriately named
        + [x] `BUILD_SWIG_PYTHON_VIRTUALENV` is not required as venv should be compulsory if building python.
    + [x] Use dependent cmake options where appropriate
        + [x] ALL_EXAMPLES will depend on FLAMEGPU2 being ON
        + [x] Individual Examples will depend on ALL_EXAMPLES being OFF (as otherwise they have no effect)

+ [x] Check consistency of `ModelDescription` hierarchy method names. Most are good, but I think i noticed a few methods on `LayerDescription` which should be new but are add (or vice versa). (via @Robadob)
+ [x] Remove dead code
   + `CUDASimulation::RTCSafeCudaMemcpyToSymbolAddress` - currenlty unused?
   + `CUDASimulation::RTCUpdateEnvironmentVariables` - currenlty usnused

**Comment by Robadob** [comment]
+ Check consistency of `ModelDescription` hierarchy method names. Most are good, but I think i noticed a few methods on `LayerDescription` which should be `new` but are `add` (or vice versa).

**Comment by Robadob** [comment]
From #375 

-[ ] Host function/condition 'callback' methods, should be renamed and use operator overloading? (was there a compatibility reason this can't be done?)

**Comment by Robadob** [comment]
> Check consistency of ModelDescription hierarchy method names. Most are good, but I think i noticed a few methods on LayerDescription which should be new but are add (or vice versa). 

I have reviewed this. The various remaining "add" methods are concerned with adding an existing agent/host function/condition to a layer or model. So I think "add" makes more sense than "new" in this context.

**Comment by ptheywood** [comment]
Ensembles and Simulation have very similar APIs, but not quite, in part due to the missing Ensemble.h (https://github.com/FLAMEGPU/FLAMEGPU2/issues/986). 

How Configs are accessed in these classes are a little different, partly due to the (missing) base, but also due to method / object names. 

https://github.com/FLAMEGPU/FLAMEGPU2/blob/19e8401f8712325b267406f91c2a1082362f90fc/include/flamegpu/gpu/CUDAEnsemble.h#L111-L115

vs 

https://github.com/FLAMEGPU/FLAMEGPU2/blob/19e8401f8712325b267406f91c2a1082362f90fc/include/flamegpu/sim/Simulation.h#L127-L128

and

https://github.com/FLAMEGPU/FLAMEGPU2/blob/19e8401f8712325b267406f91c2a1082362f90fc/include/flamegpu/gpu/CUDASimulation.h#L265

https://github.com/FLAMEGPU/FLAMEGPU2/blob/19e8401f8712325b267406f91c2a1082362f90fc/include/flamegpu/gpu/CUDASimulation.h#L277


---

Is this worth adddressing somehow?

**Comment by Robadob** [comment]
> *config stuff*
> Is this worth adddressing somehow?

Only thing I can see worth addressing would be to rename `EnsembleConfig` to `Config` as presumably it's already nested within `CUDAEnsemble`.

**Comment by Robadob** [comment]
> `HostAgentInstance` - Does not represent one individual but the whole population.

No sign of `HostAgentInstance` in the codebase any more, I've no idea what it previously referred to (`HostAgentAPI`?)

**Comment by ptheywood** [comment]
Closing this as the changes suggested that will be made have already been made. 

CUDA separation of concerns to support non cuda implementations is a future issue which would require a new major verison / refactor anyway.
