### ISSUE TITLE
Ensemble of multiple concurrent (or sequential) simualtions

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#245]
ABMs typically need to be run many times as an ensemble to get useful results.

Baking this into FLAME GPU 2 would enable small models on the GPU to be worthwhile, by providing concurrency across the simulations (and within each simulation).

The following is a rough outline of what `main` would look like for an ensemble of simulations, factoring in:

+ The ability to run 1 simulation, or an ensemble of N simulations.
+ Different (environment) parameters per ensemble
    + Model specifies default values
    + Parmeter set(s) specify overriding values, per simulation (very draft)
+ Implements a `Simulator`, individual `Simulation`s grouped as an `Ensemble`
    + Some form of aggregate operations over the results of an `ensemble` (very draft)
+ Populations are produce by the `simulator`, and may be re-used, or copied for differnt simulations, or different population can be use. 
    + Unique ID generation would be moved to the `simulator`, so they are either unique for an agent type across all `simulations`, or can be limited to the simulation.
    + Populations would also have an index alongside the id, which is relative to that population.

Again, this is again very draft / early thoughts.

```cuda


int main(int argc, char*argv[]){

    // Specify the model as usual 
    FLAMEGPU::model::ModelDescription model("model");
    // ... 

    // Create a simulator object, fixing the model
    FLAMEGPU::simulation::CUDASimulator simulator(model);
    // Initialise the simulator with cli. 
    simulator.initialise(argc, argv);

    // Generate a population of agents
    const unsigned int INITAL_POP = 8;
    FLAMEGPU::population::AgentPopulation population = simulator.newPopulation(model.agent("agent"), INITAL_POP);

    for (FLAMEGPU::population::AgentInstance &agentInstance : population) {
        // Set values, can use the index within the population, or the global id from the simulation.
        circleInstance.setVariable<float>("x", agentInstance.index() % 2;
        circleInstance.setVariable<float>("y", agentInstance.id() % 2;
    }


    {
        // Can run a single simulation
        FLAMEGPU::simulation::Simulation simulaton = simulator.simulation();
        simulation.setPopulation(model.agent("agent"), population);
        // Override environment variables 
        simulation.environment.setVariable<int>("seed", 12);
        // run the simulation 
        simulation.simulate();
    }


    {
        // Or could run an ensemble of simulations, including a way of sampling parameters 

        // Get the ensemble
        const unsigned int ENSEMBLE_SIZE = 4;
        FLAMEGPU::simulator::Ensemble ensemble = simulator.ensemble(ENSEMBLE_SIZE);

        // Define some form of parameter set, to be sampled by the ensemble.
        FLAMEGPU::simulator::ParameterSet parameterSet = ensemble.ParameterSet();
        // add a range based parameter. Name must match model.environment? 
        parameterSet.addParameterRange<int>("seed", 1, ENSEMBLE_SIZE);
        // Add a distribution to sample from? (Very very very draft)
        parameter.addParameterDistribution<std::normal_distribution<float>>("gauss", {5, 12});
        // Register this  with the ensemble.
        ensemble.registerParameterSet(parameterSet);

        // Iterate the ensemble, setting them up / having access to parameters if needed? This might allow parameters to be used to set multiple environment vars.
        for (auto &simulation: ensemble){
            auto parameters = simulation.parameterSet();
            auto seed = parameters.getValue<int>("seed");
            // maybe then simulation.environment.setValue<int>("seed", seed);

            // Set the population. Could be per simualtion, re-use the same (differnet instances, same IDs) or re-use but with unique ids through different methods on the population.
            simulation.setPopulation(population.clone());

            // Could do each sim sequentially here, via simulation.simulate()
        }

        // Or launch all simulations with concurrency. This would require lots of thinking about how to deal with simulations growing too large to fit on the device at the same time - likely move simulations to disk, and resume later.
        // Possibly pass options for tuning concurrency, or limiting concurrency. Could also specify launching over multiple GPUs.

        ensemble.simulate();

        // finally, once all simulations have completed, perform some aggregate operations. This would require variable logging / simulation objects to have some form of variables, 

        ensemble.aggregate(); // print / write output to disk?

        // Of iterate the simulations for manual aggregation?
        double totalTime = 0.0;
        for(auto simulation: simulator.ensemble()){
            // I.e. if the simulation object stores it's runtime, save to disk
            totalTime += simulation.runtime();
        }
        double averageRuntime = totalTime / ensemble.size();


    }

```

Care will need to be taken with concurrent simulations, especially w.r.t environments and general use of `cuRVE` and the limited `__constant__` cache.

**Comment by dentarthur** [comment]
As well as ensembles of small models on a single GPU node it will be useful to do ensembles of large models on an internet grid. Ensembles do not need HPC low latencies for internode communications so do not need to wait for integration of FLAME-HPC with FGPU and resolution of complex issues for overlapping computation and communications etc given the much larger mismatch for GPUs.

The only exascale computer currently available is the millions of PCs in the folding at home network, being used for developing anti-virals. There are also many others at petaflop scale eg several coordinated via BOINC.

See also AiiDA:
https://github.com/FLAMEGPU/FLAMEGPU2_dev/issues/275#issuecomment-636623944

**Comment by ptheywood** [comment]
The execution of an ensemble could be handeled in several different ways, with impacts on performance. 

1. Use multiple host threads, to indepenedenlty run multiple simulations on the same device.
    + Simple, cleaner mapping to running on multiple devices, but will not help performance in very small cases
2. for (a subset of) concurrent simulations, use the saem kernel launch across many models. 
    + Would support running many simulations with only a few agents, with (hopefully) good performance
    + Environment/buffers/curve/message lists/individual agents will need to track which simulation they belong to, which will have a performance implication.

Regardless of how this works internally care is going to be needed, and ideally the user-visible portion of the interface will be the same (with optional configuration/ hinting?)

I.e. running multiple simulations which grow populations will impact how many concurrent simulations fit on the device at once. 

Care will need to be taken with RNG. Ideally each simulation should use it's own random number sequences / seeded sequences for determinism between running a simulations concurrently or sequentialyl. 

I.e running a simulation seeded with `12` followed by seeded with `13` should be achievable concurrently.
How seeds are specified may need to be accounted for in the cli / as a parameter to the ensemble.

**Comment by Robadob** [comment]
I've updated @ptheywood's draft example here to what I would expect we're working with.
https://gist.github.com/Robadob/076ce990e560ba9042009ece65a6af99

**Comment by ptheywood** [comment]
Should use the cuda default stream per thread compiler option to support the MT approach with fewer code changes.  https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/

**Comment by Robadob** [comment]
Worth closing this, and making a new issue for discussion regarding ~`CUDASegmentedSim`?
