### ISSUE TITLE
Persistent / Non-Persistent Message Lists

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#247]
In FLAME GPU1 (and current default in FLAME GPU 2) The contents of a message list persists into the next iteration, until the first output function of the iteration. 

Supporting non-persistant messages may enable memory optimisations (sharing buffers) + be useful in some cases, where the same message list could be shared within the model. 

This should be exposed when the message list is defined? / as an extra function on the `MessageListDescription` (or similar class )

**Comment by Robadob** [comment]
Extra function on MessageDescription would be fine. Just needs to be added to `MsgBruteForce::Data` and `MsgBruteForce::Description` respectively. (I think all the other message types inherit from these)

https://github.com/FLAMEGPU/FLAMEGPU2_dev/blob/master/include/flamegpu/runtime/messaging/BruteForce.h#L288

Obviously, needs to be added to the copy constructor and equality methods too:
https://github.com/FLAMEGPU/FLAMEGPU2_dev/blob/master/src/flamegpu/runtime/messaging/BruteForce.cu#L31
https://github.com/FLAMEGPU/FLAMEGPU2_dev/blob/master/src/flamegpu/runtime/messaging/BruteForce.cu#L39

**Comment by ptheywood** [comment]
@mondus has declared that message lists should not persist (and should never have done in F1?).

**Comment by ptheywood** [comment]
Among the required changes for this, is that `CUDASimulation::reset()` does not clear the PBM, so bucket message filters which only check the pbm ratehr than checking the message count itself were still finding messages. 

i.e.
```
    // Cull messagelists
    for (auto &a : message_map) {
        a.second->setMessageCount(0);
        a.second->setTruncateMessageListFlag();
        a.second->setPBMConstructionRequiredFlag();
    }
```

Other changes are probably required to make sure that persistence is not allowed.
