### ISSUE TITLE
Interaction of step() and simulate() in Simulation/CudaSimulation

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#265]
We should clearly define (and document) the interaction between step() and simulate() within the context of a simulation, and how it may interact with exposing the current step to the user.

Expected use is that a user will call `simulate()` to run the configured number of steps. 

Alternatively users may wish to call `step()` for individual simualtion steps (i.e. integration with custom visualisations in flamegpu1).

However, if `step()` has been called, currently `simulate()` will run for `--steps` regardless (i.e. if `steps` is 12, 13 iterations would have been called.

Additionally, what should happen with multiple calls to `simulate()` (with or without calls to `reset())`, and how does this affect the step counter?

What happens to the result of exitConditions in this case? (forwarded by the returnvalue of `step` currently).

We could:

+ Block `simulate()` from being called after `step()` - make it explicitly unsupported.
+ Allow `step()` and `simualte()` to be called before/after each other, but:
    + Add a parameter to `simulate` so that it will run N steps (which defaults to `--steps` if not passed?
    + And/Or Only run simulate() until `--steps` has been achieved including prior runs (via `step_count`)?

How visualisation is implemented makes this more complex too - should `step()` be callable by the user if a visualisation is present?

+ [x] Resolve the `step()` vs `simulate()` decision
+ [x] Decide how this fits with `reset()`
+ [x] Let users call `INIT` and `EXIT` functions themselves if `step() can be called.
+ [x] Decide / document for exit conditons work with `step()`'d simulations

**Comment by Robadob** [comment]
Looking at `step()` visualisation should currently work regardless whether `step()` or `simulate()` is used.

**Comment by mondus** [comment]
Part of this is sorted in Concurrency feature.

**Comment by ptheywood** [comment]
`step()` is going to continue calling Exit Conditions and return a boolean indicating if the sim should continue or not. It is up to the user to handle this. Subsequent calls to step will continue to execute.

This will be documented, but as it is not intended use it is not as high priority as other documentation / code changes.

https://github.com/FLAMEGPU/FLAMEGPU2-docs/issues/34
