### ISSUE TITLE
Model/Simulation chaining

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#269]
Running multiple simulations/models one after another which interact is potentially useful. 

I.e. for models with a complex initialisation step (primage)

1. define an initialisation model/simulation that
2. Initialise the population
3. run the initialisation model
4. get the updated initialised population from the initialisation model
5. Define the main model/simulation
6. set the population of the main model using the  population from the initialisation model
7. run the main model

This might need more thought considering ensembles (#245) and requires #246

**Comment by dentarthur** [comment]
See also AiiDA.
https://github.com/FLAMEGPU/FLAMEGPU2_dev/issues/275#issuecomment-636623944
Add FGPU to existing simulation chaining

**Comment by ptheywood** [comment]
Going to close this for now, as this can essentially be addressed using submodels for each sequential part of the model, with the main model being another submodel, with the only downside the loss of the use of `--steps`. This can always be re-opened at a later date.
