### ISSUE TITLE
Atomically Mutable Environment Variables

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#308]
FLAME GPU 1 only has environmental variables, which are mutable from the host (as they are `__constant__`.

FLAME GPU 2 so far has environmental constants and environmental variables, where constants cannot be changed one initialised (i.e. `PI`) and variables which can be modified from the host.

It would also be useful to have environmental variables which are atomically mutable from within device code, i.e. for debug counters. 

These would need to be accessed and modified through specific methods which wrap the appropriate CUDA atomic operations, such as `atomicInc`, `atomicDec`, `atomicAdd`, `atomicSub` and `atomicExch` (maybe others). 

Care would be required when reading these variables within a layer which also contains mutations to those variables, as this would very easily lead to unintended/unexpected behaviour / care would be required with them in general.
This could possibly controlled/prevented by dependency analysis, although this would require extra information on the agent function description objects.

**Comment by Robadob** [comment]
I've been thinking about these in the context of `CUDAEnsemble` logging and the validation counters I use heavily when ensuring primage model correctness (#397).

For my requirements, I'd personally require a separate data type e.g. 'counters', that can be atomically incremented (or we could stretch as far as manipulated for more general applications). These would then be read by accessible in host code, and `CUDASimulation`/`CUDAEnsemble` logging.

Functionally, they would also load addresses via curve, but these would then be operated on atomically.

Personally, I mostly use them for validation which in part can lead to extra runtime cost. So it would be nice if a further CMake flag could silently disable them, similar to `NO_SEATBELTS`. I'm not however sure how this would fit alongside making them available for regular model operation (Primage may require them for the CA grid thing, but we did discuss alternate strategies).

**Comment by Robadob** [comment]
Closed by #643
