### ISSUE TITLE
Python Template Repository

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#349]
Once python bindings (#174) is implemented in master (#291) then a variant of [FLAMEGPU/flamegpu2_example_template](https://github.com/FLAMEGPU/flamegpu2_example_template/) should be produced as `FLAMEGPU/FLAMEGPU2_python_example_template` or similar

+ [x] Create Python example template repository, ported to the python interface
+ [x] Update readme to reflect this.
+ [x] Expand / improve the readme of the new template repo
+ [x] Change the example to be circles to match the c++ template? 
    + https://github.com/FLAMEGPU/FLAMEGPU2-python-example-template/pull/1

**Comment by Robadob** [comment]
Whilst we can do this, are we sure Python users will want to build the library themselves?
Are they not assumed less technical, and more likely to download a pre-built distribution, and hence not require any of the CMake faff?

**Comment by ptheywood** [comment]
We currently don't have a published verison anywhere, so this is the only option for now if we want early python users. 

there's also the issue of cmake time configurations to deal with in the case of pre-built distributions (SEATBELTS, CUDA_ARCH, NVTX, Release/Debug, .... ) which would need to be planned for in how it's distributed.

**Comment by Robadob** [comment]
CUDA_ARCH everything
then 2 releases:
Dev: Release, NVTX_OFF, SEATBELTS
Release: Release, NVTX_OFF, NO_SEATBELTS
We should perhaps build both of these to different names, so people can simply change `_dev` to `_release` in the import statement to swap.

I don't really think there's a case for python users needing NVTX, they should only be profiling their own code, aka agent functions. As they are not doing library development (if they are, they can build their own custom thing).

**Comment by ptheywood** [comment]
I've now created a very basic python template example, using the existing boids python implementation as the reference. 

 https://github.com/FLAMEGPU/FLAMEGPU2-python-example-template/settings/access

It needs some work, but should be sufficient for us to link to it from the main readme in the first alpha release, and we can improve it over time. 

Might be worth swtiching it to be a circles implemenation to match  the cuda c++ template.

**Comment by ptheywood** [comment]
I think it's probably OK to close this once https://github.com/FLAMEGPU/FLAMEGPU2-python-example-template/pull/1 is merged. The Readme is in an OK state, It will just need continuous improvement with the other standalone repo(s)
