### ISSUE TITLE
Separate SWIG into submodules

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#431]
SWIG doesn't automatically handle namespaces, so everything exists at the root of the `pyflamegpu` module.

This has two downsides.
* Having the entire SWIG interface in a single cxx file, means can't take advantage of parallel compilation.
* Lose the context of the purpose of items. e.g. `Stock::Models::ICOSPHERE` becomes `pyflamegpu.ICOSPHERE`, `ModelData::DEFAULT_STATE` becomes `pyflamegpu.DEFAULT_STATE`

The visualisation would benefit most from this use of modules.

**Comment by Robadob** [comment]
Not sure that I tried `pyflamegpu.ModelData.DEFAULT_STATE`

**Comment by Robadob** [comment]
I started trying to move the visualiser class `Color` and it's namespace `Stock::Colors` into a submodule `pyflamegpu`.

I essentially went through the SWIG `CMakeLists.txt`, updating it so that source files took a list, and all previously applied operations to `flamegpu.i` were applied to both swig source files.

`colors.i` looked like this (using `%module pyflamegpu.colors` here gives a syntax error)

```swig
%begin %{
// define SWIG_PYTHON_INTERPRETER_NO_DEBUG on windows debug builds as pythonXX_d is not packaged unless built from source
#ifdef _MSC_VER
#define SWIG_PYTHON_INTERPRETER_NO_DEBUG
#endif
%}

%module colors

%{
#include "flamegpu/visualiser/color/Color.h"
%}

%include "flamegpu/visualiser/color/Color.h"
```

I also updated `pyflamegpu.i`, removing `%include "flamegpu/visualiser/color/Color.h"`, replacing it with `%import(module="pyflamegpu.colors") "colors.i`.


This builds, and both object files appear to be placed into `pyflamegpu.pyd`, however when running the venv. I get no module named `pyflamegpu.colors`.

So I duplicated the call to CMake's `swig_add_library()` (and all the tens of ones configuring compilation.), and it's still a WIP. I'm getting pretty tired of fighting this for the time being, so will probably push progress to a branch.

**Comment by Robadob** [comment]
Pete further looked into this, and found it would probably mean that the main lib would have to be statically linked against each submodule, multiplying the total binary file size. So may be less viable.

**Comment by ptheywood** [comment]
Regarding pyhon namespace packages, if we had `pyflamegpu/pyflamegpu/__init__.py` and `pyflamegpu/visualiser/__init__.py` on the python path then there would be the namespace package `pyflamegpu` which contains the actual python packages `pyflamegpu` and `visualiser`, accessible via `import pyflamegpu.pyflamegpu` and `import pyflamegpu.visualiser`.
This is the modern way to do it according to the setup tools docs, so in practice we might have to use teh more complex older way of doing it with `pkg_resources`, if we went down this route. It seems that the [native method is python3.3+](https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package) though which would be fine.

I'm not sure how this would influence package management on pip however.
