### ISSUE TITLE
Improve SWIG Exceptions

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#441]
Exceptions thrown by the C/C++ code which propagate up through the SWIG interface lose their detailed error messages as only their type is forwarded. This should be improved.

This will likely impact all the python tests which check for exception type. But should be fixable with a simple find-replace across the python tests.

Curiously our current implementation uses `SWIG_Python_Raise()` which is not found across the whole swig 3 docs.

SWIG Docs re exceptions: http://www.swig.org/Doc3.0/SWIGDocumentation.html#Python_nn44

**Comment by Robadob** [comment]
The detailed error message is available via `e.value.what()`, not sure how I missed this the first time.

Might be possible to get rid of the `value`, however that's a separate issue of much lower priority.

**Comment by ptheywood** [comment]
Does this get shown to the user when an error is thrown from python?

**Comment by Robadob** [comment]
I don't believe so.

**Comment by Robadob** [comment]
Some testing has shown that adding the python to string method to `FGPURuntimeException` defined inside `flamegpu.i` improves the output.

```c
    const char* __str__() const {
         return err_message.c_str();
     }
```

becomes

```
pyflamegpu.pyflamegpu.FGPURuntimeException: C:/Users/Robadob/fgpu2/swig/python/../../include\flamegpu/model/AgentDescription.h(259): Agent ('Agent1') already contains variable 'Var1', in AgentDescription::newVariable().
```


I also tried replacing `__repr__` hoping it would let me control the `pyflamegpu.pyflamegpu.FGPURuntimeException` part, however this is not the case.

**Comment by Robadob** [comment]
With #501 unhandled exception output now looks like

```
Traceback (most recent call last):
  File "error.py", line 14, in <module>
    a.newVariableInt64(VARIABLE_NAME1) # InvalidAgentVar exception
  File "C:\Users\Robadob\fgpu2\build\lib\windows-x64\python\venv\lib\site-packages\pyflamegpu\pyflamegpu.py", line 2569, in newVariableInt64
    return _pyflamegpu.AgentDescription_newVariableInt64(self, variable_name, default_value)
pyflamegpu.pyflamegpu.FGPURuntimeException: (InvalidAgentVar) C:/Users/Robadob/fgpu2/swig/python/../../include\flamegpu/model/AgentDescription.h(259): Agent ('Agent1') already contains variable 'Var1', in AgentDescription::newVariable().
```
