### ISSUE TITLE
RTC Agent functions from source file

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#459]
@mileach has suggested that it might be nice to make it possible to load each RTC agent function from its own source file. 

I.e. Rather than in main having 

```
const char * output_message = R"###(
FLAMEGPU_AGENT_FUNCTION(output_message, MsgNone, MsgSpatial3D) {
    FLAMEGPU->message_out.setVariable<int>("id", FLAMEGPU->getVariable<int>("id"));
    FLAMEGPU->message_out.setLocation(
    FLAMEGPU->getVariable<float>("x"),
    FLAMEGPU->getVariable<float>("y"),
    FLAMEGPU->getVariable<float>("z"));
    return ALIVE;
}
)###";

// ....

agent.newRTCFunction("output_message", output_message).setMessageOutput("location");

// ... 

LayerDescription &layer = model.newLayer();
layer.addAgentFunction("Circle", "output_message");

```
Instead you have a separate file `Circle_output_message.rtc.cuh` (or something to that effect)

```
// Might need #include?

FLAMEGPU_AGENT_FUNCTION(output_message, MsgNone, MsgSpatial3D) {
    FLAMEGPU->message_out.setVariable<int>("id", FLAMEGPU->getVariable<int>("id"));
    FLAMEGPU->message_out.setLocation(
    FLAMEGPU->getVariable<float>("x"),
    FLAMEGPU->getVariable<float>("y"),
    FLAMEGPU->getVariable<float>("z"));
    return ALIVE;
}
```

Which can then be specified as a source file for a cudaModel through some new method. 

Advantages:

+ Syntax highlighting
+ *Maybe* possible to get NVCC to build it at compile time for compile time validation of syntax
+ *Maybe* more suitable for debugging? Very unsure on this though.

Probably still want to keep the `const char *` option around though, as you can could dynamically generate the agent function.

**Comment by Robadob** [comment]
> `// Might need #include?`

You would need the include for smart code highlighting, e.g. intellisense.

This would however need to be removed prior to RTC compilation (or rtc doing some fudging to make that header point to an empty file), otherwise I think it collides with the RTC dynamic header.


> Maybe possible to get NVCC to build it at compile time for compile time validation of syntax

I'd rather we come up with a post-compile (pre-link?) build step that does rtc compilation and packages it into the executable somehow. More difficult, but would fix the user experience.

Wouldn't be a benefit to SWIG though.

**Comment by Robadob** [comment]
> I'd rather we come up with a post-compile (pre-link?) build step that does rtc compilation and packages it into the executable somehow. More difficult, but would fix the user experience.

From a visual studio perspective it would be along the lines of make the files `.cu_rtc` file type, and then add a `.props` file that handles their compilation. Not sure how we'd tell CMake to set that up though.

**Comment by Robadob** [comment]
754b44dd
