### ISSUE TITLE
No tests present for host function conditions

### ISSUE THREAD

**Issue by MILeach** [FLAMEGPU/FLAMEGPU2#473]
There don't appear to be any tests associated with host function conditions. Agent function conditions are tested quite thoroughly so this seems like an omission.

**Comment by MILeach** [comment]
Exit conditions are tested which is perhaps sufficient?

**Comment by Robadob** [comment]
Yes, exit condition is the only form of host function condition currently. The generic macro just exists for parity.

**Comment by Robadob** [comment]
Perhaps better clarified as, FLAMEGPU1 has global function conditions, which were essentially  (very limited) host function conditions. But Paul is satisfied with submodels replacing this functionality.
