### ISSUE TITLE
Linting flamegpu2/visualiser from standalone example

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#478]
Linting all or the main lib / visualiser from standalone examples reports many errors. 

Arguably linting these from individual examples should not be required, or alternateively I think the fix is to ensure that cpplint runs from the correct directory (i.e. `_deps/flamegpu2-src` I think, or the `root` arg needs specifying appropriately)

**Comment by Robadob** [comment]
In general visualiser lint has a problem. It expects include paths to begin with `src/`.

**Comment by Robadob** [comment]
> In general visualiser lint has a problem. It expects include paths to begin with src/.

I think this can be closed. Linting visualiser works from my standalone fgpu2 primage project.

**Comment by Robadob** [comment]
FLAMEGPU2 is however unhappy

For basically every header:

```
1>C:/Users/Robadob/primage/fgpu2nb/build/_deps/flamegpu2-src/include/flamegpu/sim/AgentInterface.h(1): error cpplint: [build/header_guard] #ifndef header guard has wrong style, please use: BUILD__DEPS_FLAMEGPU2_SRC_INCLUDE_FLAMEGPU_SIM_AGENTINTERFACE_H_ [5]
```
