### ISSUE TITLE
Github Actions Annotations

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#480]
Annotations are a newer github actions feature that clearly show warnings/errors without having to manually inspect the log. 

Some of the actiosn from the marketplace for running linters or compilers may emit these, but they might also not do things we want them to. 

An alterantive it is to post-process the output using sed/awk/grep and emit the relevant statements which the workflow runner will pick up on. 
Although this will complicate our action a little,  it might be better than executing random third party actions.

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

**Comment by Robadob** [comment]
gcc/visual studio have standard compiler output formats, I would expect there are public regex's or similar for extracting warnings/errors from logs.

**Comment by ptheywood** [comment]
see https://github.com/ptheywood/actions-playground/pull/15 for a demo. 

This is very crude still / needs adding per build step in it's current form, which needs thinking about

**Comment by Robadob** [comment]
For convenience, they show up at the bottom of these pages.

![image](https://user-images.githubusercontent.com/742154/112469122-fe6f0e80-8d60-11eb-9817-f0b98175b9f3.png)
![image](https://user-images.githubusercontent.com/742154/112469162-0cbd2a80-8d61-11eb-88f7-e3cc797a0c2c.png)

**Comment by ptheywood** [comment]
They show up in the files chagned tab too at the appropriate line. On the checks tab you have to click on the speech bubble icon, whcih takes you to the individual build.

![image](https://user-images.githubusercontent.com/628937/112469730-b8667a80-8d61-11eb-9120-a53d609404cd.png)

**Comment by Robadob** [comment]
I didn't spot that, even better.

**Comment by ptheywood** [comment]
[Problem Matchers](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) seem like they could be the best answer for this (found while looking into adding annotations from `pa11y` to encourage documentaiton accessibility testing elsewhere). I might try this out if I have some short idle time to see if it works.
