### ISSUE TITLE
Messagelist size insufficient when two agents write to same list.

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#488]
**Describe the bug**
Message list is not resized big enough when two agents output to same message list (in the same layer?).
[This](https://github.com/FLAMEGPU/FLAMEGPU2/blob/034d2ac7b5906202612f01eb0f76cf341def5f6e/src/flamegpu/gpu/CUDAMessage.cu#L288) assert is triggered. message_count = 512, newMsgCount = 512, max_list_size = 711.

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a model where two agent functions output to the same (Spatial3D) message list in the same layer
2. Run model

**Expected behaviour**
a) Throw a proper exception at model definition time saying two agents can't output to same message list in same layer
~b) Model work as intended as message list is resized correctly.~

**Comment by Robadob** [comment]
From discussing with @ptheywood it should be a limitation that only 1 agent fn per layer can output to  a message list. Presumably, important that @MILeach 's dependency work #458 enforces this rule too.

**Comment by ptheywood** [comment]
It should just need adding to `LayerDescription::addAgentFunction` which I believe will also make it be considered in the current implementaiton of the DAG based approach 

Tests should be added looking for the exception too. 

As somewhere to put a list of restrictions off the top of my head, which may be incomplete (we should probabyl have a nice version of this in the docs somewhere)

+ Sub models must be in their own layer
+ Host functions must be in their own layer
    + Although they are executed sequentially, if we added say openmp based parallelism it would be very easy to break things.
+ Agent functions in the same layer:
     + No agent functions where the same agent state is involved (start or end states) 
        + This could be achieved in some cases(no death, mututalle exclusive conditions?), but simpler to just prevent it (for now) 
     + No agent functions where birth occurs into another agent state which is active in another agnet fn
         + this should be possible if we are careful, its probably just safer to block it (for now)
     + No message output into a list which is already in the layer (input or output)
        + a function which iterates a message list and then outputs to that same message list should be allowed
     + Probably other restrictions...

**Comment by Robadob** [comment]
> Host functions must be in their own layer
> No agent functions where birth occurs into another agent state which is active in another agnet f

I don't believe these are currently enforced either.

> No message output into a list which is already in the layer (input or output)

Damn, only handled both message out in my PR.
