### ISSUE TITLE
Example Suite Repository/Repositories

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#603]
The plan is to separate out the examples into thier own repository(s), allowing them to be versioned separately to the core library.

Potentially with some cmake to allow a "fetch me the examples and build them all please" option or somethign to that effect. This may cause a version / dependency loop though, so it might be better to have a separate repo with all examples that also pulls in FLAMEGPU2's core repository. 

This will then allow generation of executables at a different release candence to the main library (and mean that any fixes to say `boids_spatial3D` does not implicitly lead to a new library release (if not neccesary).

**Comment by Robadob** [comment]
Fine with me.
Minimum request being we add examples/* to git ignore, so I've atleast got a hacky way of keeping some minimal example around for debugging.

**Comment by ptheywood** [comment]
The alternative would be that we adjust the examples cmake to make it easy to specify FLAMEGPU_ROOT or similar pointing at a separate local directory, but yeah no harm in keeping examples in .gitignore either.

**Comment by Robadob** [comment]
Yeah, I suppose the inverse might work better. A hidden `EXAMPLES_ROOT` option to enable a non-rtc and rtc example for testing in main repo.

**Comment by ptheywood** [comment]
An alternative (or additional point) may be to split the current `examples` directory into subfolders to distinguish between C++ and python examples. Probably better not to use `+` in a directory path though, so `cxx`?

**Comment by ptheywood** [comment]
During meeting splitting the examples out or not prior to rc1 was discussed, concluding that: 

+ We don't want any heavy-weight examples in the main repo, to keep the lib itself lighter (i.e. no massive vis objects or input state files)
+ The chicken-and-egg version dependency issues of pulling in versioned examples to the main repo via a flag makes it not worth splitting out but allowing to pull in from the main repo.
  + Having standalone examples which pull in a speicfic version is OK/Good though
+ Folders are a good idea, to split the examples into:
  + Python (`python`)
  + c++ interface (`CUDA`? `cxx`? `CUDACXX`?)
  + c++ RTC interface (`RTC`? `(CUDA/cxx/CUDAcxx)RTC`
  + c++ not actual models but rather demonstrations of features
    + I.e. `ensemble` so we have an ensemble binary to build and test the CLI.
    + Alternatively we could just make it an actual ensemble of a given model? 
+ The host functions example is not super useful, as the tests + docs cover this use case too. If another example covers the host angle though, this could safely be removed.

**Comment by ptheywood** [comment]
Closed by #1010
