### ISSUE TITLE
Allow users to specify include directories for RTC

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#607]
Advanced users may have math header libraries, similar to GLM they wish to include or other external headers. Currently we don't allow users to specify their own include directories for RTC.

Obviously, there are natural NVRTC limitations to this, so would require being well documented that not all CUDA supported headers will work out of the box (e.g. if Jitify safe headers are lacking).

This is relatively low priority, but also should be fairly trivial to support.

**Comment by ptheywood** [comment]
This mechanism would also be useful for enabling NVHPC (#563) support, where curand is not installed within the `CUDA_HOME` directory (although for non-RTC builds we probably need an additional fix / a recent enough cmake version)

**Comment by Robadob** [comment]
Closed by #801
