### ISSUE TITLE
Do not install pip packages into the current environment

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#639]
During CMake configuration with `-DBUILD_SWIG_PYTHON` several pip packages are automatically installed into the current python environment if they are not found.

This might just be the users default python environment.

If so, it is poor form to do this without any kind of prompt to the user. 

I believe this should have been covered by a previous issue, but I couldn't find it. I previously had done some work on performing everything in a venv within the build directory as part of #285, but ran into issues with Windows so stopped working on that if i remember correctly.

Related to #267 and probably others.

**Comment by mondus** [comment]
Make wheel a dependency and fix later.
