### ISSUE TITLE
Example: Pedestrian

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#64]
Models showing pedestrian simulations. FLAME GPU 1 includes 2 examples, which may not both be required

+ [ ] PedestrianLOD (requires sorting #52 and visualisation #69 for this to be required)
+ [ ] PedestrianNavigation

**Comment by Robadob** [comment]
FYI, I have no plans to implement LOD support in the vis, but I think it should be possible with currently functionality (once anim PR is merged).

**Comment by Robadob** [comment]
https://github.com/FLAMEGPU/FLAMEGPU2-pedestrian_navigation-example
