### ISSUE TITLE
EnsembleConfig::devices in Swig/python.

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#682]
`CUDAEnsemble::EnsembleConfig::devices` is a `std::set<int>`.

 This does not appear to be well-wrapped by swig currently, so is not (obviously) usable from python (other than via the CLI)

The current command line argument takes a comma separated string of non-negative integers, which is parsed into a `std::set`.

Although uniqueness is useful, it might be worth using an order-preserving data structure (although probably not neccesary). This might also help if Swig is not great with sets, as we know it's usable with vectors. It could then be converted to a set at time of use.

**Comment by Robadob** [comment]
swig has a `std_set.i` file, so it might just need to be included.

Found in `_deps\swig-src\Lib\python`

**Comment by Robadob** [comment]
Have fixed this, PR coming soon.

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyflamegpu
>>> model = pyflamegpu.ModelDescription("m")
>>> sim = pyflamegpu.CUDAEnsemble(model)
>>> sim.Config().devices
<pyflamegpu.pyflamegpu.IntSet; proxy of <Swig Object of type 'std::set< int > *' at 0x0000024C2061E090> >
>>> for a in sim.Config().devices:
...   print(a)
...
>>> sim.Config().devices+=1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +=: 'IntSet' and 'int'
>>> sim.Config().devices.add(1)
>>> for a in sim.Config().devices:
...   print(a)
...
1
>>> sim.Config().devices.add(1333)
>>> sim.Config().devices.add(1)
>>> for a in sim.Config().devices:
...   print(a)
...
1
1333
```
