### ISSUE TITLE
Cannot programatically set default, cli-overrideable config values 

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#755]
The `random_seed` for a `Simulation` cannot be programaticlaly set to a non-time based value default value which can be overridden by the cli parsing of `initialise(argc, argv)`, as initialise resets values to default. 

This will apply to other configuration values.

**Comment by Robadob** [comment]
https://docs.flamegpu.com/guide/8-running-multiple-sims/4-multiple-sims.html

This is `CUDAEnsemble` (so probably not got the same behaviour), but the bugged practice is being demonstrated in docs here (right at the bottom).

**Comment by ptheywood** [comment]
`CUDAEnsemble` doesn't reset to defaults on calls to initialise

https://github.com/FLAMEGPU/FLAMEGPU2/blob/34cd8268bf6a6740d755d54b3d18a3becf08a46b/src/flamegpu/gpu/CUDAEnsemble.cu#L172-L182


https://github.com/FLAMEGPU/FLAMEGPU2/blob/34cd8268bf6a6740d755d54b3d18a3becf08a46b/src/flamegpu/sim/Simulation.cu#L36-L45

**Comment by Robadob** [comment]
Yeah, as a minimum they should be consistent.
I suggest that `CUDASimulation` is changed, but it's a 'breaking' change.
