### ISSUE TITLE
Handling NaN/Inf in JSON Output

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#762]
Based on an issue Kenneth was having, it would appear that under FGPU2, if a float (or array) containing `NaN`, is exported that particular value (or array) is simply omitted. Leading to invalid JSON, and in the case of the array loss of data.

It could be better if we handle this, by replacing `NaN` with 0 and writing a warning to stderr. Same probably applies to `INF` too, though I've never achieved that by mistake.

(Or we work out how to enable RapidJSON to break standards and output NaN, but iirc there's a bunch of compiler compatibility issues trying to enable that).

**Comment by ptheywood** [comment]
Breaking the JSON spec seems unwise, as it will prevent downstream use of the JSON files in cases which do not support it.

From a quick search it seems that encoding the values as `0` or as `"NaN"` seem to be commonly used.

There seem to be a few alternate json-like specs that support NaN, though I'm not sure how wide-spread they are (i.e. JSON5) that could be an alternate input/output format that includes NaN and INF (either via a flag for JSON input/output, or a separate set of classes?)
