### ISSUE TITLE
Diffusion Example

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU2#780]
Would be very useful for multiscale modelling and woudl be trivial to implement with Array2D messaging. Some good reference to analytic approaches at the following link: https://enccs.github.io/OpenACC-CUDA-beginners/2.02_cuda-heat-equation/

**Comment by Robadob** [comment]
Started working on that example, then noticed it does von-neumann neighbourhood, rather than Moore. We don't have that.
