### ISSUE TITLE
setAgentOutputOptional in Python interface

### ISSUE THREAD

**Issue by isolin** [FLAMEGPU/FLAMEGPU2#795]
According to [docs](https://docs.flamegpu.com/guide/6-agent-birth-death/1-agent-birth-device.html) it should be possible to set an opt-in for agent birth for a `newRTCFunction` using `agent_fn1_description.setAgentOutputOptional(true)`. However, I am getting `AttributeError: 'AgentFunctionDescription' object has no attribute 'setAgentOutputOptional'`. Please also fix the Booelan value, as Python uses `True` instead of `true`.

My code:
```py
fnPlantReceivesEnvironment = plant.newRTCFunction("plant_receives_environment", plant_receives_environment)
fnPlantReceivesEnvironment.setMessageInput("soil_msg")
fnPlantReceivesEnvironment.setMessageOutput("plant_soil_msg")
fnPlantReceivesEnvironment.setAgentOutput(plant)
fnPlantReceivesEnvironment.setAgentOutputOptional(True) #ERROR HERE
```

I'm using `pyflamegpu_vis-2.0.0a2+cuda112-cp38-cp38-linux_x86_64.whl`.

**Comment by Robadob** [comment]
Docs website has just updated, page is now correct: https://docs.flamegpu.com/guide/6-agent-birth-death/1-agent-birth-device.html

**Comment by isolin** [comment]
Thank you very much :+1:
