### ISSUE TITLE
Memory on device 0 is always used.

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2#820]
CUDA Context is being created on device 0, before device is switched.

This example causes the below NVIDIA SMI output (note nvidia smi IDs don't match cuda device IDs).
```c++
flamegpu::CUDASimulation sim(model);
sim.CUDAConfig().device_id = 1
sim.applyConfig();
```

![image](https://user-images.githubusercontent.com/742154/159954499-bf92ef69-027e-4cc1-9df6-8770cff409ce.png)

@ptheywood thinks he previously fixed this and it may have regressed, needs some investigation.

As of [620e904](https://github.com/FLAMEGPU/FLAMEGPU2/commit/620e9047300e0bf2b113655cfd038a240dd664e3) (after the shared mem curve merge) this is still an issue.

**Comment by ptheywood** [comment]
Using the cli `-d 1` and checking via nvidia-smi and via nsys for the spatial_3D example doesn't reproduce this (with 0501279a0d23aa45ee12889138830894ff4f415d), neither does setting the device programatically. 

```
    flamegpu::CUDASimulation cudaSimulation(model);

    cudaSimulation.CUDAConfig().device_id = 1;
    cudaSimulation.applyConfig();
```


```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1434      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      1434      G   /usr/lib/xorg/Xorg                 12MiB |
|    1   N/A  N/A      1476      G   /usr/bin/sddm-greeter              18MiB |
|    1   N/A  N/A    178261      C   ...n/Release/boids_spatial3D      312MiB |
+-----------------------------------------------------------------------------+
```

Either it has been fixed uninentationally, or there is something model specific / not in the above MWE which is causing utilsitaion of the not requested device.

**Comment by Robadob** [comment]
Maybe it's Primage model specific (somehow?). I'll have to check there.
