### ISSUE TITLE
Accessing multiple message lists within one agent function

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#86]
The XML schema for FLAMEGPU 1 models makes it appear as if iterating messages from multiple lists would be possible (i.e. `<inputs>` with an `s`). 
This isn't actually possible (most likely due to the AoS -> shared memory struct mapping making this complicated, but it would be useful in some cases.

**Comment by Robadob** [comment]
With the templated messaging now in place, to provide a message handler for specific MsgType, this isn't going to happen.
