### ISSUE TITLE
Add Host/Device API agent `getIndex` method

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#898]
Add a method to get an agents index within a population as part of the FLAME GPU API (for host and device code?)

This will be the index within the current population, so the value is ephemeral and may change for a given agent between functions (i.e. if the order changes due to death / birth / state changes / generic sorting). 

For a CUDA backend, this is effectively the global thread id, but should be possible for non-CUDA implementations too (and the value will be known for agent data to be accessible anyway). 

Needs to clearly be distinct from ID, and needs to be well documented as only valid at the time the method was called. 

---

This will then be used in conflict resolution within the prospective schelling implementation

**Comment by Robadob** [comment]
Device API already has `getThreadIndex()`, and although they're not really intended to use direct agent access on Host, surely just the index the agent appears within the `DeviceAgentVector` is what you're after?

**Comment by ptheywood** [comment]
for current device code, this is just a redirect / rename of `getThreadIndex`, which is also explicitly part of the public API (`getThreadIndex` feels like something we probably implemented for ourselves really). The justification being that in a (theoretical) CPU based implementation where we would be unlikely to spin up a whole CPU thread for each agent, so getting the index within the population executing the current agent function is desired. 

In current host / step functions, it would be the index within the current `AgentVector`. If users are useing range-based for loops rather than iterating by index, they might not have this readily available. It is basically syntactic sugar on the host. For an iterator, it's just the distance from `begin()` I guess?. 

It's mostly about making the public API less cuda-shaped for if / when there are alternate backend.

**Comment by Robadob** [comment]
> It's mostly about making the public API less cuda-shaped for if / when there are alternate backend.

You'll want to rename "host functions" then.

**Comment by mondus** [comment]
I think having a host vs "compute device" abstraction is still ok so would argue that "host functions" are semantically ok. The important thing is the abstract the detail of the underlying device implementation which is why `getIndex` is required.
