### ISSUE TITLE
CUDAEnsemble CLI output shows progress incorrectly

### ISSUE THREAD

**Issue by zeyus** [FLAMEGPU/FLAMEGPU2#901]
**Describe the bug**
This is an extremely minor issue. When CUDAEnsemble outputs its progress to the console, it will say how many runs it has completed e.g. 4/10. The problem is the number on the left, seems to just be the index of the first missing log (or the result from one thread I'm not sure). So when I was doing runs, some exit early if the agents die, and with 4 threads let's say threads 3 and 4 finish, then log files 0 and 1 are missing, it will quickly report 2/10 complete then go to 0/10.

**To Reproduce**
Steps to reproduce the behaviour:

Make a CUDAEnsemble with multiple threads, set some later threads to terminate early.

**Expected behaviour**
The number should be the total simulation runs completed.

**Configuration(please complete the following information):**
 - OS: Win 11
 - CUDA version: 11.7
 - GPU GTX 1070
 - GPU Driver Version  516.59

**Comment by Robadob** [comment]
Yeah I'm aware of this, thought there was an issue, guess not.

Afaik, the progress lists the index of the last job  to finish, so if they end out of order they were started the progress counter can go backwards.

**Comment by Robadob** [comment]
This is the offending line of code

https://github.com/FLAMEGPU/FLAMEGPU2/blob/e176d8ae5a267148387ac9500a051ce5de253014/src/flamegpu/sim/SimRunner.cu#L106

The solution *might* be to replace `run_id + 1` with `next_run.get() + <number of runners> - 1`.

The total number of runners would need to be passed to the `SimRunner` at construction though.
