### ISSUE TITLE
Swig CMake incremental build missing dependency?

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#979]
When I split the swig building into multiple CMake targets for better incremetnal builds, I missed adding a depenceny on the `PYTHON_SWIG_TARGET_NAME` target to make it depend on the pyflamegpu header files? 

I.e. currently it is possible to get `flamegpuPYTHON_wrap.cxx` file compilation errors when the header files have changed on disk, but CMake thinks it's up to date. 

It might be a bit of a timestamp race to achieve this, via cancelling builds and checking out between branches

I think this is because `swig_add_library` depends only on `${SWIG_INPUT_FILE_NAME}.i` with a link depenceny on `flamegpu`, so the cxx generation is only tied to the `.i` timestamp and not also the header files. Just passing the list of header files as SOURCES too should resolve this based on the UseSwig docs?

**Comment by Robadob** [comment]
Is this issue not that `flamegpu.i` does not depend on the entire flamegpu header hierarchy?

**Comment by Robadob** [comment]
You realise that a `.cpp` file depends on the full hierarchy of includes it references. This is essentially the same thing required for `flamegpu.i`.

**Comment by ptheywood** [comment]
In a CMake context, `flamegpu.i` is a file, only targets can have depenencies.

**Comment by Robadob** [comment]
I'm thinking Visual Studio land. It's a file, which is built with a custom build tool. Within visual studio it's possible to specify dependencies for the file, No idea how CMake would handle that.

![image](https://user-images.githubusercontent.com/742154/202278939-061a6f07-d79d-445a-9753-b21858cbf4da.png)

**Comment by ptheywood** [comment]
Passing the list of header files from the `flamegpu` target as sources to `swig_add_library` (see below) doesn't seem to have impacted the dependency rules as hoped

```
# Get the header files from the flamegpu target, to specify as sources for the swig library to ensure it is regenerated if a header is changed
get_target_property(FLAMEGPU_HEADERS flamegpu SOURCES)
list(FILTER FLAMEGPU_HEADERS INCLUDE REGEX ".*\.(h|hpp|cuh)$")
# Add swig module via the native CMake integration integraiton.
swig_add_library(${PYTHON_SWIG_TARGET_NAME}
	TYPE SHARED
	#TYPE STATIC
	LANGUAGE python
	OUTPUT_DIR ${PYTHON_LIB_TEMP_DIRECTORY}/${PYTHON_MODULE_NAME}
	SOURCES ${SWIG_INPUT_FILE_NAME}.i ${FLAMEGPU_HEADERS}
  )
unset (FLAMEGPU_HEADERS)
```

```
cat swig/python/CMakeFiles/pyflamegpu_swig_swig_compilation.dir/DependInfo.cmake

# Consider dependencies only in project.
set(CMAKE_DEPENDS_IN_PROJECT_ONLY OFF)

# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  "CXX"
  )
# The set of files for implicit dependencies of each language:
set(CMAKE_DEPENDS_CHECK_CXX
  "/home/ptheywood/code/flamegpu/FLAMEGPU2/swig/python/flamegpu.i" "/home/ptheywood/code/flamegpu/FLAMEGPU2/build/swig/python/CMakeFiles/pyflamegpu_swig.dir/flamegpuPYTHON.stamp"
  )
set(CMAKE_CXX_COMPILER_ID "GNU")

# The include file search paths:
set(CMAKE_CXX_TARGET_INCLUDE_PATH
  )

# The set of dependency files which are needed:
set(CMAKE_DEPENDS_DEPENDENCY_FILES
  )

# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
```

```
cat swig/python/CMakeFiles/pyflamegpu_swig.dir/DependInfo.cmake

# Consider dependencies only in project.
set(CMAKE_DEPENDS_IN_PROJECT_ONLY OFF)

# The set of languages for which implicit dependencies are needed:
set(CMAKE_DEPENDS_LANGUAGES
  )

# The set of dependency files which are needed:
set(CMAKE_DEPENDS_DEPENDENCY_FILES
  "/home/ptheywood/code/flamegpu/FLAMEGPU2/build/swig/python/pyflamegpu/flamegpuPYTHON_wrap.cxx" "swig/python/CMakeFiles/pyflamegpu_swig.dir/pyflamegpu/flamegpuPYTHON_wrap.cxx.o" "gcc" "swig/python/CMakeFiles/pyflamegpu_swig.dir/pyflamegpu/flamegpuPYTHON_wrap.cxx.o.d"
  )

# Targets to which this target links.
set(CMAKE_TARGET_LINKED_INFO_FILES
  "/home/ptheywood/code/flamegpu/FLAMEGPU2/build/FLAMEGPU/CMakeFiles/flamegpu.dir/DependInfo.cmake"
  "/home/ptheywood/code/flamegpu/FLAMEGPU2/build/FLAMEGPU/CMakeFiles/tinyxml2.dir/DependInfo.cmake"
  )

# Fortran module output directory.
set(CMAKE_Fortran_TARGET_MODULE_DIR "")
```

---

CMake 3.20 (or CMake 3.22 for VS) introduces 

> USE_SWIG_DEPENDENCIES
> New in version 3.20.
> 
If set to TRUE, implicit dependencies are generated by the swig tool itself. This property is only meaningful for [Makefile](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#makefile-generators), [Ninja](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#ninja-generators), [Xcode](https://cmake.org/cmake/help/latest/generator/Xcode.html#generator:Xcode), and [Visual Studio](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators) ([Visual Studio 11 2012](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2011%202012.html#generator:Visual%20Studio%2011%202012) and above) generators. Default value is FALSE.
> 
> New in version 3.21: Added the support of [Xcode](https://cmake.org/cmake/help/latest/generator/Xcode.html#generator:Xcode) generator.
> 
>New in version 3.22: Added the support of [Visual Studio Generators](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators).

When enabled under linux via 
```
set_property(SOURCE ${SWIG_INPUT_FILE_NAME}.i PROPERTY USE_SWIG_DEPENDENCIES TRUE)
```

This changes the order of swig processing, so that flamegpu builds prior to the `Swig compile flamegpu.i for python` step, which does solve the issue, but only for very recent swig. This would find the required deps too theoretically. 

Given we have a manual list of the headers available, we might be able to use the `DEPENDS` source file property of the `.i` file rather than listing them as sources. 

---

Setting `DEPENDS` manually seems to work, with swig compilation occuring earlier than `flamegpu`, but being triggered on header editing so this seems to be the best fix for us.
